### ISSUE TITLE
Cannot successfully build

### ISSUE THREAD

**Issue by dayizhang** [SingleTact/InterfaceBoardFirmware#1]
Output file not found: robo_si.omf

**Comment by kubkon** [comment]
Can you try now and let me know if anything else is missing?

**Comment by dayizhang** [comment]
it looks like after debug, "robo_si.omf" will be removed, it still display Output file not found: robo_si.omf

**Comment by kubkon** [comment]
Can you try and fix it then, and submit a patch?

**Comment by dayizhang** [comment]
* RESTRICTED VERSION WITH 0800H BYTE CODE SIZE LIMIT; USED: 11D1H BYTE (222%) *
It looks like size over limit, Tiantian talked last week.

**Comment by gordondobie** [comment]
Fixed

On Wednesday, 9 December 2015, Jakub Konka <notifications@github.com> wrote:

> Assigned #1
> <https://github.com/SingleTact/InterfaceBoardFirmware/issues/1> to
> @gordondobie <https://github.com/gordondobie>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SingleTact/InterfaceBoardFirmware/issues/1#event-486783670>
> .
>


-- 
Sent from Gmail Mobile
